### ISSUE TITLE
Table 1 of your paper

### ISSUE THREAD

**Issue by HireTheHero** [Nithin-Holla/meme_challenge#2]
Hi, thanks for giving me the insights on hateful memes.

Ragarding table 1 of [your paper](https://arxiv.org/abs/2012.12871), how did you define `unimodal hate`?
For benign confounders my best guess is you used [ConfounderSampler. _find_confounders](https://github.com/Nithin-Holla/meme_challenge/blob/f4dc2079acb78ae30caaa31e112c4c210f93bf27/data/meme_dataset.py#L232) to collect the flip of the modality, but unfortunately couldn't find the clues for the other labels so far.

Thanks!

**Comment by HireTheHero** [comment]
In addition do you have reference for how to detect image confounder?

**Comment by phlippe** [comment]
Hi, `unimodal hate` is defined in the dataset paper by Kiela et al. [1] as data points "where one or both modalities were already hateful on their own". This label cannot be extracted from non-annotated data as easily as the confounders.

Image confounders can be detected by measuring image similarity. However, since we did not make use of image confounders in our approach, we do not have code for it in this repository.

[1] Douwe Kiela, Hamed Firooz, Aravind Mohan, Vedanuj Goswami, Amanpreet Singh, Pratik Ringshia, and Davide Testuggine. 2020. The hateful memes challenge: Detecting hate speech in multimodal memes. NeurIPS 2020

**Comment by HireTheHero** [comment]
Thanks @phlippe, what kind of approach did you take to label `unimodal hate` for table 1?

**Comment by phlippe** [comment]
The statistics from Table 1 were gathered from Kiela et al. and communications with the organizers during the competition. We did not label these ourselves, nor had access to the labels.

**Comment by HireTheHero** [comment]
Makes sense, thanks!
